### ISSUE TITLE
how to train my own model ? 

### ISSUE THREAD

**Issue by macro-dadt** [mdietrichstein/yolo-tiny-v1-mobile#2]
first of all, very nice repro. i could run successfully based on your instruction. Now i want to train new model on my own dataset (VOC dataset). The point is that i cant get a new weight file after training. Please give some clues if you have any experiment in this stuff. Thanks in advance !!!

**Comment by macro-dadt** [comment]
update: i can train my own model by using darkflow.now how i can change your code to conform with my model (number of classes is not 20), i figure out that your repro work perfectly with model which have 20 classes

**Comment by mdietrichstein** [comment]
Hey @macro-dadt 

The whole process is quite involved and would require changes to the export and inference code. The idea of documenting the process of adapting the current code to a new model sounds interesting though.

I'd be willing to create the documentation/notebooks describing the process. I'd need some help from you though: I have never retrained a darkflow model before. Do you have some information describing the process? Training data would be awesome too.
