### ISSUE TITLE
Not creating YOLO-tiny_tf.weight or output images with bounding box

### ISSUE THREAD

**Issue by hardikchauhan8** [mdietrichstein/yolo-tiny-v1-mobile#3]
Hello,

I have set up all the dependencies for this demo and also run the first notebook successfully but it does not create 'yolo-tiny_tf.weights' or did not show the output image of cars with bounding boxes over them.

can you please help me or tell me if i am doing something wrong?

**Comment by hardikchauhan8** [comment]
I did manage to create the weights file but still, output images are not generated.
And am receiving multiple errors/warnings like,

> /usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:36: RuntimeWarning: invalid value encountered in power
> /usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in power

> /usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in greater

```
ValueError                                Traceback (most recent call last)
<ipython-input-30-cb37c2b2b87e> in <module>()
      1 f,(ax1,ax2) = plt.subplots(1,2,figsize=(16,6))
----> 2 ax1.imshow(mark_objects(boxes, resized_image))
      3 ax2.imshow(mark_objects(boxes, original_image));

<ipython-input-29-cb66386a8e48> in mark_objects(boxes, image)
      7         x1, y1, x2, y2, confidence, class_index = b
      8 
----> 9         left  = int (x1 * w)
     10         right = int (x2 * w)
     11         top   = int (y1 * h)

ValueError: cannot convert float NaN to integer
```

**Comment by mdietrichstein** [comment]
Hey @nightfox8 

Which OS are you using (Mac, Windows, OSX, ...), also which versions of the following packages do you use: `python`, `tensorflow`, `keras`, `opencv`?
