### ISSUE TITLE
Problem running apk

### ISSUE THREAD

**Issue by foromer4** [mdietrichstein/yolo-tiny-v1-mobile#4]
Having a problem running on Android device: Error:Execution failed for task ':app:packageDebug'.
 Execution of compression failed

Clean/ rebuild doesn't help.
some version info:

  ext.kotlin_version = '1.1.3-2'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
 
...
 ext.kotlin_version = '1.1.3-2'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

 Many thanks

**Comment by mdietrichstein** [comment]
Try increasing the heap size as described at https://stackoverflow.com/a/47689687

If that does not work, could you try running `./gradlew clean assembleDebug --debug --stacktrace` and paste the log output here?

**Comment by foromer4** [comment]
many thanks - it works now! 
Indeed it was an "out of memory" issue .
If I may , I would also like to point out that the optimized.yolo.pb is used , however in the readme it says to copy the forzen_yolo.pb.
And also, the current frame rate is about ~2 seconds per frame  (on redmi note 4), is that what's expected? I can move these questions to different issues if preffred.
thanks again-  cool project!

**Comment by mdietrichstein** [comment]
> If I may , I would also like to point out that the optimized.yolo.pb is used , however in the readme it says to copy the forzen_yolo.pb.

Thanks for pointing that one out! I've fixed the README.

> And also, the current frame rate is about ~2 seconds per frame (on redmi note 4), is that what's expected?

That's about the fps I have observed on my test devices as well. I plan to port the app over to Tensorflow Lite to check if this will improve the performance. 

> I can move these questions to different issues if preffred.

Sure, go ahead :)
