### ISSUE TITLE
Where can I find a pre-trained model?

### ISSUE THREAD

**Issue by takasurazeem** [mdietrichstein/yolo-tiny-v1-mobile#6]
The file frozen_yolo.pb is missing, where can I find that file? I seem to have trouble generating my own.

**Comment by shivaji17** [comment]
the repository does not contain optimized_yolo.pb.....from where can I get it..???

**Comment by mdietrichstein** [comment]
The model files exceed github's file size limit, that's why you have to generate them using the jupyter notebooks. Please open a new issue for problems regarding the notebooks.
